# Generated by Django 3.2.7 on 2021-09-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20210915_0919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='requestForm',
        ),
    ]
