# Generated by Django 3.2.7 on 2021-09-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_requestform_received_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='responseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=100)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.requestform')),
            ],
        ),
    ]
