# Generated by Django 3.2.7 on 2021-09-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_responseform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseform',
            name='request_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form.requestform'),
        ),
    ]
