# Generated by Django 3.2.7 on 2021-09-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_responseform_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseform',
            name='request_id',
            field=models.IntegerField(),
        ),
    ]
