# Generated by Django 3.2.7 on 2021-09-15 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_responseform_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='DOb',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='pin_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
