# Generated by Django 3.2.7 on 2021-09-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_alter_requestform_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseform',
            name='response',
            field=models.CharField(max_length=200),
        ),
    ]
