# Generated by Django 3.2.7 on 2021-09-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_alter_responseform_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='pin_code',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='salary',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='responseform',
            name='request_id',
            field=models.IntegerField(default=None),
        ),
    ]
