# Generated by Django 3.2.7 on 2021-09-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_auto_20210915_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseform',
            name='reason',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
