# Generated by Django 3.2.7 on 2021-09-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_responseform_reason'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requestform',
            table='request_form',
        ),
        migrations.AlterModelTable(
            name='responseform',
            table='response_form',
        ),
    ]
